# See http://docs.travis-ci.com/user/languages/julia/ and 
# https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1

# See status of Travis builds at https://travis-ci.com/kdl-umass/GPSLC

language: julia
julia:
  - 1.7

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - julia -e 'using Pkg; Pkg.build(); Pkg.test()'
    - stage: docker
      script:
        - docker build docker/ -t gen
    - stage: docs
      julia: 1.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip