[data]
    # the total number of data to generate
    n = 100

    # Sigma U
    obj_size = 2
    eps = 1e-13
    ucov = 0.9

    # Sigma X
    xvar = 1.0

    # noise for u, t, x, y (assuming Gaussian additive)
    uNoise = 1.0
    xNoise = 0.5
    tNoise = 1.0
    yNoise = 0.1

    # this field change the data type: polynomial, sinusoidal, exponential
    XTAssignment = ["polynomial"]
    UTAssignment = ["polynomial"]
    XYAssignment = ["polynomial"]
    TYAssignment = ["sinusoidal", "polynomial"] # you can stuck multiple function X + sin(X)
    UYAssignment = ["polynomial"]

    [data.XTparams]
        poly = [1.0]   # poly[1] * X + poly[2] * X^2 + ... +
        exp = [0.5, 1.0]    # exp[1] * exp(exp[2] * X)
        sin = [2.0, 2.0]    # sin[1] * sin(sin[2] * X)

    [data.UTparams]
        poly = [1.0]
        exp = [0.5, 1.0]
        sin = [1.0, 2.0]

    [data.XYparams]
        poly = [1.0]
        exp = [0.5, 1.0]
        sin = [1.0, 2.0]

    [data.TYparams]
        poly = [1.0, 0.3]
        exp = [0.5, 1.0]
        sin = [5.0, 2.0]

    [data.UYparams]
        poly = [2.0]
        exp = [0.5, 1.0]
        sin = [1.0, 2.0]


[model]
    uxLS = 10.0
    uyLS = 10.0
    xyLS = 1.0

    xNoise = 1.0
    yNoise = 0.1