dataset = "ISO"
experiment = 1

# models to evaluate
models = ["correct", "no_confounding", "no_objects", "GP_per_object", "MLM", "MLM_offset"]
posterior_dir = "results/ISO/bias1/"

# posterior samples
nOuter = 5000
burnIn = 4000
stepSize = 100
nSamplesPerPost = 100
