dataset = "ISO"
experiment = 6

# models to evaluate
models = ["correct", "no_confounding", "no_objects", "GP_per_object", "MLM", "MLM_offset"]
posterior_dir = "results/ISO/bias6/"

# posterior samples
nOuter = 5000
burnIn = 500
stepSize = 10
nSamplesPerPost = 5
