dataset = "ISO"
experiment = 10

# models to evaluate
models = ["correct", "no_confounding", "no_objects", "GP_per_object", "MLM", "MLM_offset"]
posterior_dir = "results/ISO/bias0/"

# posterior samples
nOuter = 5000
burnIn = 4000
stepSize = 10
nSamplesPerPost = 100